### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by mhgarci1** [LBLQMM/MACAW#3]
We should indicate the dependencies needed for Macaw and update the installation to recommend using conda environments. 
For example, I had a problem with sklearn-rvm. When using the conda environment, these instructions do not work (the environment cannot see the package): 

https://sklearn-rvm.readthedocs.io/en/latest/install.html#installing-the-latest-release

It is necessary to use the local environment executables:

"For others who run into this situation, I found this to be the most straightforward solution:

Run conda create -n venv_name and conda activate venv_name, where venv_name is the name of your virtual environment.

Run conda install pip. This will install pip to your venv directory.

Find your anaconda directory, and find the actual venv folder. It should be somewhere like /anaconda/envs/venv_name/.

Install new packages by doing /anaconda/envs/venv_name/bin/pip install package_name."

https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment.

We should update the installation information so as to avoid these problems.

**Comment by mhgarci1** [comment]
I found the dependencies!! They should be updated to include sklearn-rvm

**Comment by vinbl** [comment]
The package `sklearn-rvm` is used in some of the Notebooks as an application example of a machine-learning algorithm trained on MACAW embeddings. It is not required by `macaw-py` itself.

To install `sklearn-rvm`, an option is to run `pip install sklearn-rvm` in the same environment where MACAW is installed.

**Comment by vinbl** [comment]
For simplicity, `sklearn-rvm` was included as a dependency in update [1a9f28a](https://github.com/LBLQMM/MACAW/commit/1a9f28a353c9bcb9bcc315422d5530d6282d73d8)
